empresaasociada:
    pattern:  /
    defaults: { _controller: "servicioBundle:EmpresaAsociada:index" }

empresaasociada_show:
    pattern:  /{id}/show
    defaults: { _controller: "servicioBundle:EmpresaAsociada:show" }

empresaasociada_new:
    pattern:  /new
    defaults: { _controller: "servicioBundle:EmpresaAsociada:new" }

empresaasociada_create:
    pattern:  /create
    defaults: { _controller: "servicioBundle:EmpresaAsociada:create" }
    requirements: { _method: post }

empresaasociada_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "servicioBundle:EmpresaAsociada:edit" }

empresaasociada_update:
    pattern:  /{id}/update
    defaults: { _controller: "servicioBundle:EmpresaAsociada:update" }
    requirements: { _method: post }

empresaasociada_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "servicioBundle:EmpresaAsociada:delete" }
    requirements: { _method: post }
