parameters:
#    servicio.example.class: piloto\servicioBundle\Example

services:
#    servicio.example:
#        class: %servicio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
