parameters:
#    holaprue.example.class: hola\prueBundle\Example

services:
#    holaprue.example:
#        class: %holaprue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
